import Head from 'next/head';
import Layout from '../components/Layout';
import Episodes from '../components/Episodes';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Rick</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout />
      <hr />
      <Episodes />
    </div>
  );
}
